version: "3.9"

x-common-variables: &common-variables
  WAIT_HOSTS: redis:6379
  WAIT_HOSTS_TIMEOUT: 300
  WAIT_SLEEP_INTERVAL: 10
  WAIT_HOST_CONNECT_TIMEOUT: 30
  CONVERT_TO_WEBP_QUEUE: convert
  SEND_WEBP_TO_WHATSAPP_QUEUE: complete

services:
  whatsticker-master:
    build: ./master
    restart: always
    depends_on:
      - redis
    command: bash -c "/wait && go run main.go -log-level DEBUG"
    volumes:
      - type: bind
        source: ./master/db
        target: /project/db
      - images:/project/images
      - videos:/project/videos
    environment:
      <<: *common-variables
  whatsticker-worker:
    build: ./worker
    restart: always
    depends_on:
      - redis
      - metrics
    command: bash -c "/wait && go run main.go"
    volumes:
      - images:/project/images
      - videos:/project/videos
    deploy:
      mode: replicated
      replicas: 3
    environment:
      <<: *common-variables
  logger:
    build: ./logger
    restart: always
    depends_on:
      - redis
      - metrics
    command: bash -c "/wait && go run main.go"
    deploy:
      mode: replicated
      replicas: 3
    environment:
      <<: *common-variables
  redis:
    restart: always
    image: redis
  metrics:
    image: prom/pushgateway
    restart: always
    ports: 
      - 9091 

volumes:
  images:
  videos:
